### ISSUE TITLE
Error importing google/protobuf/timestamp.proto

### ISSUE THREAD

**Issue by KryptXBSA** [rsbh/nodejs-microservices#3]
First of all, Thank you for your blog post. It greatly helped me understand the process.

But I've encountered a couple of issues:

- In the packages/protos directory:

The google/protobuf/timestamp.proto file is not found, resulting in a "File not found" error, Full error:
```> @rsbh-nodejs-microservices/protos@1.0.1 build
> ./build.sh

google/protobuf/timestamp.proto: File not found.
product/product.proto:5:1: Import "google/protobuf/timestamp.proto" was not found or had errors.
product/product.proto:13:3: "google.protobuf.Timestamp" is not defined.
product/product.proto:14:3: "google.protobuf.Timestamp" is not defined.
```
I do have the protoc compiler installed, So I'm not sure why it's giving me that error.
It did compile after i changed the Timestamp type to a string.

- Also when running npm run dev on services/product-service i got this error it has something to do with module resolution:
```
nodejs-microservices/node_modules/@rsbh-nodejs-microservices/protos/product/product.ts:2
import {
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by rsbh** [comment]
@AlandSleman You can check this issue https://github.com/protocolbuffers/protobuf/issues/5131.
The protobuf compiler is not able to locate these standard proto files.

And for `Cannot use import statement outside a module` issue, can you update the `@rsbh-nodejs-microservices/protos` package to 2.1.0 in the services. I have pushed JS files along with TS to npm.
